### ISSUE TITLE
Application Freezing

### ISSUE THREAD

**Issue by boonzie** [RSATom/WebChimera.js#144]
I don't know why, but when I'm using .play() while another play is in progress it makes the app frozen.

**Comment by boonzie** [comment]
+ After CTRL + R of app video is "laggy", somehow onFrameReady event is called lower times than usual which makes video is not rendered properly on canvas

**Comment by RSATom** [comment]
What OS do you use?

**Comment by boonzie** [comment]
Windows

**Comment by hondek** [comment]
I have same issue, sometime when player playing and i click to play next video all UI freezing.

I write script who do this error every time, please download this archive, unpack, cd to folder and just "yarn dev" to get this bug.

archive: [http://quadrapps.net/wcjs-ugly-demo.7z](url)

**Comment by RSATom** [comment]
@hondek Unfortunately can't download it - always getting 403 (forbidden) error

**Comment by hondek** [comment]
@RSATom sorry it looks like forbidden out of west europe, this should work fine: [http://137.74.92.81/wcjs-ugly-demo.7z](http://137.74.92.81/wcjs-ugly-demo.7z)

**Comment by RSATom** [comment]
@hondek Yes, I was able download it. Thanks!

**Comment by RSATom** [comment]
And was able to reproduce... investigating...

**Comment by RSATom** [comment]
It hangs inside `libvlc` on `WaitForSingleObjectEx` call. For me it looks like deadlock (i.e. bug inside `libvlc`). And it worth try update `libvlc` to the latest version. I'll check it soon.

**Comment by RSATom** [comment]
@boonzie @hondek deadlock should be fixed in `v0.5.2`. Please try.

**Comment by hondek** [comment]
@RSATom it look great! thanks a lot!

**Comment by boonzie** [comment]
Working fine now

**Comment by NotixOfficial** [comment]
I would like to inform you that this problem is still not completely remedied.

Namely, the deadlock, which used to happen when loading the stream, has not been completely resolved. Sometimes it still appears and lasts only until the first frame. I just found one scenario where deadlock appears (i'm not sure if there are more scenarios)

For example, if one stream is currently being buffered, and if we switch to playing another stream, electron will freeze and it will become not responding until the video is buffered.

I'll try to take a look later, but I just want to point out that the problem remains.
